name: Test
on:
  push:
    branches:
      - master
jobs:
  rebase:
    name: Rebase master
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: master
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git rebase origin/master
          git push origin master --force
